* Price Hiller's Dots
This is a mirror from my Git server over [[https://git.orion-technologies.io/Price/dots][here]].

These are my dot files. All the actual dots can be found under ~users/price/dots/~.

I've gone pretty far to break things up and make my dots as easy as possible to install for a
new system.

In the past I was running on a Mac, so you may find some Mac specific things (especially in my
~zsh~) config.

For the record, feel free to take what you want. I'm not worried about getting contribution for
dot files. They're largely just for fun, not something important. 🙂

* TODO Various Tasks to get done [2/3]

- [X] Clean up and better modularize the config
  - Currently a large portion of this config lives in ~users/price/home.nix~ which, while ok for
    now, will get out of hand down the road
- [X] Implement automation to autoformat various paths
  - Looking through the commit history I have semi-regular ~style~ commits for formatting.
  - Would be good to add a global git hook on the client side for pre push validation
  - Would also be good to get a CI runner up that validates on the server side
- [ ] Enhance our custom ~Fmt~ program to avoid certain files.
    - I don't need to format some files that are handled automatically by other programs
- [ ] Migrate the ~Kanagawa.tmTheme~ for ~bat~ to a nix attribute set, using ~tmTheme~ for home manager's bat configuration is deprecated.
