name: Check Formatting of Files
on:
  - push
  - workflow_dispatch
jobs:
  Check-Formatting:
    runs-on: default
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Nix Flake Check
        run: |
          nix flake check
