name: Check Formatting of Files
on:
  - push
  - workflow_dispatch
jobs:
  Check-Formatting:
    runs-on: default
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Ensure ssh-agent has private keys loaded
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< '${{ secrets.SSH_KEY }}'
      - name: Nix Version
        run:
          nix --version
      - name: Nix Flake Check
        run: |
          nix flake check
