name: Check Formatting of Files
on:
  - push
  - workflow_dispatch

jobs:
  Check-Formatting:
    runs-on: default
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check formatting
        run: |
          for f in **/flake.nix; do
            nix flake lock --update-input "$(basename "$(dirname "$f")")" || true
          done
          nix flake lock --update-input Fmt
          nix --experimental-features "flakes nix-command" flake check
