name: Check Formatting of Files
on:
  - push
  - workflow_dispatch

jobs:
  Check-Formatting:
    runs-on: default
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install `Fmt` package
        run: nix --experimental-features "flakes nix-command" build 'path:./pkgs/Fmt' --out-link fmt-result

      - name: Check formatting
        run: PATH="${PATH}:${PWD}/fmt-result/bin" ./scripts/check-fmt-git-files.bash
