#+FILETAGS: :neovim:dots:

* Neovim Configuration
This is my Neovim configuration. There are many like it, but this one is mine.

I make no promises things in here are the most well thought out configuration nor capable of
working outside of the narrow scope I set up my systems in.

I am sure /much/ of it will work on any computer with a bash or zsh shell, but I don't want to
invest the effort at the time of writing to find out and make it work across a bunch of use cases.


* DONE Neogit
SCHEDULED: <2024-02-23 Fri> DEADLINE: <2024-02-25 Sun>
- [X] Determine why Neogit's diff hunks are not highlighted until I place a cursor over a hunk.
  - This was fixed upstream and with the manual foldmethod set in ~987e89c~ this is working as
    expected.
  - Right now the diffs have 0 highlighting which makes it annoying to just glance at them —
    requires manual movement of the cursor position 🫤

* DONE CI Automation
SCHEDULED: <2024-03-04 Mon> DEADLINE: <2024-03-15 Fri>
- [X] Configure a pipeline to enforce formatting via Stylua

* CANCELLED Use native Neovim snippets instead of Luasnip
SCHEDULED: <2024-05-17 Fri> CLOSED: [2024-07-16 Tue 22:46]
