# --- GROMIT-MPX ---
workspace = special:gromit,gapsin:0,gapsout:0,decorate:false,border:false,on-created-empty:gromit-mpx -a
windowrule = match:class ^(Gromit-mpx)$, no_blur on
windowrule = match:class ^(Gromit-mpx)$, opacity 1 override
windowrule = match:class ^(Gromit-mpx)$, suppress_event fullscreen maximize
windowrule = match:class ^(Gromit-mpx)$, no_shadow on
windowrule = match:class ^(Gromit-mpx)$, suppress_event fullscreen
windowrule = match:class ^(Gromit-mpx)$, no_anim on
windowrule = match:class ^(Gromit-mpx)$, no_dim on
windowrule = match:class ^(Gromit-mpx)$, size 100% 100%

# Gromit Bindings
bind = CTRLSUPER,x,togglespecialworkspace,gromit
bind = CTRLSUPER,x,submap,gromit
submap = gromit
bind = ,c,exec, gromit-mpx --clear
bind = CTRL,z,exec, gromit-mpx --undo
bind = ,z,exec, gromit-mpx --redo
bind = CTRLSUPER,x,togglespecialworkspace,gromit
bind = CTRLSUPER,x,submap,reset
bind = ,escape,togglespecialworkspace,gromit
bind = ,escape,submap,reset
submap = reset
